import type { Product, CategoryMeta } from './types'

export const products: Product[] = [
  // ── Refrigerators ─────────────────────────────────────────────
  {
    id: '1',
    name: 'Single Door Refrigerator',
    slug: 'single-door-refrigerator',
    category: 'refrigerators',
    price: 350_000,
    shortDescription: 'Compact single-door fridge ideal for small households.',
    description:
      'A reliable single-door refrigerator perfect for small families and tight spaces. Offers efficient cooling with a spacious interior, adjustable shelves, and a built-in freezer compartment to keep your food fresh longer.',
    features: [
      'Spacious interior with adjustable shelves',
      'Built-in freezer compartment',
      'Energy-efficient cooling system',
      'Easy-clean interior lining',
      'Durable door seal for optimal temperature retention',
    ],
    images: ['/fridge-single-350.jpeg', '/fridge-single-open-350.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.3,
    reviewCount: 45,
    tags: ['fridge', 'refrigerator', 'single-door'],
    createdAt: '2024-01-10',
  },
  {
    id: '2',
    name: 'SPJ Single Door Refrigerator',
    slug: 'spj-double-door-refrigerator',
    category: 'refrigerators',
    price: 3_790_000,
    shortDescription: 'Large-capacity SPJ single-door refrigerator with a dispenser for big families.',
    description:
      'The SPJ single Door Refrigerator delivers superior cooling performance with a large capacity suitable for big households. Features a separate freezer section, multiple storage compartments, and a modern design that complements any kitchen.',
    features: [
      'Large single-door design with a dispenser and separate freezers',
      'Multiple storage compartments and door shelves',
      'Energy-saving cooling technology',
      'Adjustable temperature control',
      'Frost-free operation',
    ],
    images: ['/spj-refridgerator-3.79M.jpeg'],
    badge: 'Premium',
    inStock: true,
    warranty: '2 years manufacturer warranty',
    rating: 4.7,
    reviewCount: 28,
    tags: ['spj', 'fridge', 'refrigerator', 'double-door'],
    createdAt: '2024-01-15',
  },

  // ── Washing Machines ───────────────────────────────────────────
  {
    id: '3',
    name: 'Hisense Top Load Washing Machine',
    slug: 'hisense-top-load-washing-machine',
    category: 'washing-machines',
    price: 1_850_000,
    shortDescription: 'Hisense top-load washer with multiple wash programs.',
    description:
      'The Hisense Top Load Washing Machine delivers powerful, reliable cleaning for the whole family. With multiple wash programs and a large drum capacity, it handles everything from delicate fabrics to heavily soiled laundry with ease.',
    features: [
      'Multiple wash programs for all fabric types',
      'Large drum capacity',
      'Fuzzy Logic Control for optimal washing',
      'Child lock safety feature',
      'Low water and energy consumption',
    ],
    images: ['/Hisense-wshing-1.85.jpeg'],
    inStock: true,
    warranty: '2 years manufacturer warranty',
    rating: 4.5,
    reviewCount: 62,
    tags: ['hisense', 'washing-machine', 'top-load'],
    createdAt: '2024-01-20',
  },
  {
    id: '4',
    name: 'Twin Tub Washing Machine',
    slug: 'twin-tub-washing-machine',
    category: 'washing-machines',
    price: 820_000,
    shortDescription: 'Dual-tub semi-automatic washer with separate spin dryer.',
    description:
      'The Twin Tub Washing Machine offers the convenience of a separate wash tub and spin dryer, giving you full control over your laundry cycle. Ideal for medium-sized households, it cleans efficiently and spins clothes nearly dry.',
    features: [
      'Separate wash and spin tubs',
      'Semi-automatic operation for flexible use',
      'Timer control for wash and spin cycles',
      'Lint filter for cleaner clothes',
      'Compact design easy to store',
    ],
    images: ['/Twin-tub-washing-machine-820k.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.2,
    reviewCount: 38,
    tags: ['washing-machine', 'twin-tub', 'semi-automatic'],
    createdAt: '2024-01-22',
  },
  {
    id: '5',
    name: 'Midea Automatic Washing Machine',
    slug: 'midea-automatic-washing-machine',
    category: 'washing-machines',
    price: 1_700_000,
    shortDescription: 'Fully automatic Midea washer with smart wash technology.',
    description:
      'The Midea Fully Automatic Washing Machine brings smart washing technology to your home. With multiple automatic cycles and powerful motor performance, it delivers consistent, thorough cleaning while being gentle on fabrics.',
    features: [
      'Fully automatic operation',
      'Multiple wash cycles including quick wash',
      'Powerful yet quiet motor',
      'Imbalance detection and auto-correction',
      'Digital display with program selection',
    ],
    images: ['/midea-washing-1.7m.jpeg'],
    badge: 'New Arrival',
    inStock: true,
    warranty: '2 years manufacturer warranty',
    rating: 4.6,
    reviewCount: 54,
    tags: ['midea', 'washing-machine', 'automatic'],
    createdAt: '2024-02-01',
  },

  // ── Televisions ────────────────────────────────────────────────
  {
    id: '6',
    name: 'CHiQ 32" HD Smart TV',
    slug: 'chiq-32-hd-smart-tv',
    category: 'televisions',
    price: 400_000,
    shortDescription: 'CHiQ 32-inch HD smart TV with built-in streaming apps.',
    description:
      'The CHiQ 32" HD Smart TV delivers crisp high-definition visuals with a built-in smart platform for streaming your favourite content. Its slim design and vibrant display make it perfect for bedrooms, kitchens, and small living spaces.',
    features: [
      '32-inch HD (1366×768) display',
      'Built-in smart TV platform with streaming apps',
      'HDMI and USB connectivity',
      'Dolby Audio for clear sound',
      'Screen mirroring and casting support',
    ],
    images: ['/chiq-400k-32.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.3,
    reviewCount: 91,
    tags: ['chiq', 'tv', 'smart-tv', 'hd', '32-inch'],
    createdAt: '2024-01-18',
  },
  {
    id: '7',
    name: 'CHiQ 40" Full HD Smart TV',
    slug: 'chiq-40-full-hd-smart-tv',
    category: 'televisions',
    price: 700_000,
    shortDescription: 'CHiQ 40-inch Full HD smart TV with vivid display.',
    description:
      'The CHiQ 40" Full HD Smart TV offers an immersive viewing experience with its Full HD 1080p panel, smart connectivity, and clear audio. Ideal for living rooms and family entertainment, it brings your favourite shows and movies to life.',
    features: [
      '40-inch Full HD (1920×1080) display',
      'Smart TV with popular streaming apps pre-installed',
      'HDMI, USB, and AV connectivity',
      'Clear Motion technology for smooth video',
      'Energy-saving LED backlight',
    ],
    images: ['/chiq-40inch-700k.jpeg'],
    badge: 'Best Seller',
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.5,
    reviewCount: 118,
    tags: ['chiq', 'tv', 'smart-tv', 'full-hd', '40-inch'],
    createdAt: '2024-01-18',
  },

  // ── Cookers ────────────────────────────────────────────────────
  {
    id: '8',
    name: 'SPJ Full Gas Tabletop Cooker',
    slug: 'spj-full-gas-tabletop-cooker',
    category: 'cookers',
    price: 380_000,
    shortDescription: 'SPJ 4-burner tabletop gas cooker with an oven and auto-ignition.',
    description:
      'The SPJ Full Gas Tabletop Cooker combines practicality and efficiency in a compact countertop design. Equipped with auto-ignition burners and a sturdy stainless steel body, it heats up quickly and distributes heat evenly for consistent cooking results.',
    features: [
      '4-burner tabletop design',
      'Auto-ignition for easy start',
      'Durable stainless steel body',
      'Cast iron pan supports for stability',
      'Compatible with standard LPG gas cylinders',
    ],
    images: ['/380k%20spj-full-gas.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.4,
    reviewCount: 73,
    tags: ['spj', 'gas-cooker', 'tabletop', 'cooker'],
    createdAt: '2024-02-05',
  },
  {
    id: '9',
    name: 'SPJ Free-Standing Gas Cooker',
    slug: 'spj-free-standing-gas-cooker',
    category: 'cookers',
    price: 550_000,
    shortDescription: 'SPJ free-standing gas cooker with 2 cooking coils, oven and grill.',
    description:
      'The SPJ Free-Standing Gas Cooker is a full-featured kitchen appliance combining a multi-burner hob with a built-in oven and grill. Perfect for families who love to cook a variety of meals, it offers versatility and reliability in one unit.',
    features: [
      'Multi-burner hob for simultaneous cooking',
      'Built-in oven with grill function',
      'Auto-ignition on all burners',
      'Oven interior light for easy monitoring',
      'Sturdy stainless steel finish',
    ],
    images: ['/spj-550k.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.5,
    reviewCount: 57,
    tags: ['spj', 'gas-cooker', 'standing', 'oven', 'cooker'],
    createdAt: '2024-02-10',
  },
  {
    id: '10',
    name: 'SPJ 4-Burner Gas Cooker with Oven',
    slug: 'spj-4-burner-gas-cooker-oven',
    category: 'cookers',
    price: 990_000,
    originalPrice: 1_100_000,
    shortDescription: 'Premium SPJ 4-burner gas cooker with large oven.',
    description:
      'The SPJ 4-Burner Gas Cooker with Oven is the ultimate cooking companion for busy households. Four powerful burners provide flexibility for multiple dishes at once, while the spacious oven is perfect for roasting, baking, and grilling.',
    features: [
      '4 high-efficiency gas burners of varying sizes',
      'Large oven with multiple rack positions',
      'Separate grill section',
      'Auto-ignition on all burners',
      'Tempered glass oven door',
      'Easy-clean enamel interior',
    ],
    images: ['/spj-cooker-990k.jpeg'],
    badge: 'Best Seller',
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.7,
    reviewCount: 84,
    tags: ['spj', 'gas-cooker', '4-burner', 'oven', 'cooker'],
    createdAt: '2024-01-05',
  },
  {
    id: '11',
    name: 'Four Burner Gas Plate',
    slug: 'four-burner-gas-plate',
    category: 'cookers',
    price: 300_000,
    shortDescription: 'Compact four-burner gas plate for quick, portable cooking.',
    description:
      'The Four Burner Gas Plate is the perfect solution for quick meals, small kitchens, and outdoor cooking. Lightweight and portable, it connects easily to any standard LPG cylinder and delivers consistent, controllable heat.',
    features: [
      'Four high-output burners for versatile cooking',
      'Lightweight and portable design',
      'Compatible with standard LPG gas cylinders',
      'Cast iron pan support for stability',
      'Adjustable flame control knob',
    ],
    images: ['/gas-plate-300k.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.1,
    reviewCount: 112,
    tags: ['gas-plate', 'gas-cooker', 'single-burner', 'portable'],
    createdAt: '2024-01-25',
  },
  {
    id: '12',
    name: 'Blueflame Microwave',
    slug: 'blueflame-microwave',
    category: 'microwaves',
    price: 250_000,
    shortDescription: 'Affordable Blueflame microwave for everyday use.',
    description:
      'The Blueflame Microwave is an affordable and reliable kitchen essential. Its compact design fits neatly on any countertop, making it a practical choice for rental kitchens, student hostels, and everyday home cooking.',
    features: [
      'High-efficiency heating technology',
      'Compact tabletop design',
      'Easy-to-use digital controls',
      'Large interior capacity for family meals',
      'Quick heating and defrosting functions',
    ],
    images: ['/blueflame-250k.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.2,
    reviewCount: 95,
    tags: ['blueflame', 'microwave', 'kitchen-appliance'],
    createdAt: '2024-01-12',
  },
  {
    id: '13',
    name: 'Hoffmans Infrared Electric Cooker',
    slug: 'hoffmans-infrared-electric-cooker',
    category: 'cookers',
    price: 250_000,
    shortDescription: 'Energy-efficient Hoffmans infrared electric cooker.',
    description:
      'The Hoffmans Infrared Electric Cooker uses advanced infrared heating technology to cook food faster and more efficiently than conventional electric cookers. It heats up instantly, reduces energy waste, and is easy to clean with its flat glass surface.',
    features: [
      'Infrared heating element for rapid, even cooking',
      'Flat tempered glass surface — easy to wipe clean',
      'Adjustable temperature settings',
      'Overheat protection for safety',
      'Energy-efficient operation',
    ],
    images: ['/Hoffmans-infrared-250k.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.3,
    reviewCount: 67,
    tags: ['hoffmans', 'infrared-cooker', 'electric-cooker', 'cooker'],
    createdAt: '2024-01-30',
  },
  {
    id: '14',
    name: 'Happy Home 2-Burner Gas Cooker',
    slug: 'happy home-2-burner-gas-cooker',
    category: 'cookers',
    price: 250_000,
    shortDescription: 'Happy Home 2-burner tabletop gas cooker for daily cooking.',
    description:
      'The Happy Home 2-Burner Gas Cooker is a dependable kitchen appliance for everyday cooking. With a sturdy build and efficient burners, it delivers reliable performance for boiling, frying, and simmering at an affordable price.',
    features: [
      '2-burner tabletop design',
      'Durable stainless steel body',
      'Manual ignition with robust knobs',
      'Stable cast-iron pan supports',
      'Standard LPG cylinder connection',
    ],
    images: ['/HappyHome-250k.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.1,
    reviewCount: 43,
    tags: ['happyhome', 'gas-cooker', 'cooker'],
    createdAt: '2024-02-08',
  },
  {
    id: '15',
    name: 'Happy Home 5-Burner Gas Cooker',
    slug: 'happy home-5-burner-gas-cooker',
    category: 'cookers',
    price: 400_000,
    shortDescription: 'Happy Home 5-burner gas cooker with enamel pan supports.',
    description:
      'The Happy Home 5-Burner Gas Cooker offers maximum cooking flexibility with five burners for preparing multiple dishes simultaneously. Its robust construction and practical design make it the ideal choice for busy family kitchens.',
    features: [
      '5 gas burners of varying sizes',
      'Enamel-coated pan supports',
      'Durable stainless steel top',
      'Manual ignition on each burner',
      'Compact and space-efficient design',
    ],
    images: ['/happyHome-400k.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.3,
    reviewCount: 51,
    tags: ['happyhome', 'gas-cooker', '5-burner', 'cooker'],
    createdAt: '2024-02-12',
  },

  // ── Air Fryers ─────────────────────────────────────────────────
  {
    id: '16',
    name: 'Hoffmans Digital Air Fryer',
    slug: 'hoffmans-digital-air-fryer',
    category: 'air-fryers',
    price: 350_000,
    shortDescription: 'Hoffmans digital air fryer for healthy, oil-free cooking.',
    description:
      'The Hoffmans Digital Air Fryer uses rapid hot-air circulation to fry, roast, and bake your favourite foods with little to no oil. Enjoy crispy chips, chicken wings, and baked goods that are healthier without sacrificing taste.',
    features: [
      'Rapid air circulation technology',
      'Up to 80% less oil than traditional frying',
      'Digital temperature and timer control',
      'Non-stick removable basket, dishwasher safe',
      'Multiple cooking presets for popular dishes',
    ],
    images: ['/hoffmans-Airfryer-350k.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.5,
    reviewCount: 88,
    tags: ['hoffmans', 'air-fryer', 'healthy-cooking'],
    createdAt: '2024-02-03',
  },
  {
    id: '17',
    name: 'Kenwood Air Fryer',
    slug: 'kenwood-air-fryer',
    category: 'air-fryers',
    price: 400_000,
    shortDescription: 'Kenwood large-capacity air fryer with multi-cook functions.',
    description:
      'The Kenwood Air Fryer delivers professional-quality results at home. With a large basket capacity and multiple cooking functions including air fry, roast, bake, and grill, it handles everything from snacks to full family meals effortlessly.',
    features: [
      'Large basket capacity for family-sized portions',
      'Multiple functions: air fry, roast, bake, grill',
      'Adjustable temperature up to 200°C',
      'Built-in timer with auto-shutoff',
      'Easy-clean non-stick basket and drawer',
    ],
    images: ['/kenwood-airfryer-400k.jpeg'],
    badge: 'Popular',
    inStock: true,
    warranty: '2 years manufacturer warranty',
    rating: 4.6,
    reviewCount: 103,
    tags: ['kenwood', 'air-fryer', 'healthy-cooking'],
    createdAt: '2024-02-06',
  },

  // ── Rice Cookers ───────────────────────────────────────────────
  {
    id: '18',
    name: 'Oriamo Electric Rice Cooker',
    slug: 'oriamo-electric-rice-cooker',
    category: 'rice-cookers',
    price: 250_000,
    shortDescription: 'Oriamo automatic rice cooker with keep-warm function.',
    description:
      'The Oriamo Electric Rice Cooker makes perfectly fluffy rice every time, automatically switching to keep-warm mode when done. A must-have kitchen appliance for rice lovers, it also doubles as a steamer for vegetables and dumplings.',
    features: [
      'Automatic cook-to-warm switching',
      'Non-stick inner pot for easy cleaning',
      'Steam vent lid for safe pressure release',
      'Includes rice measure cup and serving spoon',
      'Compact design suitable for any kitchen',
    ],
    images: ['/oriamo-rice-cooker-250k.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.4,
    reviewCount: 76,
    tags: ['oriamo', 'rice-cooker', 'electric'],
    createdAt: '2024-01-28',
  },
  {
    id: '19',
    name: 'Pixel Electric Rice Cooker',
    slug: 'pixel-electric-rice-cooker',
    category: 'rice-cookers',
    price: 250_000,
    shortDescription: 'Pixel automatic rice cooker with non-stick inner pot.',
    description:
      'The Pixel Electric Rice Cooker delivers consistently perfect rice with minimal effort. Its automatic cooking cycle ensures rice is cooked through without burning, then keeps it warm and ready to serve whenever you need it.',
    features: [
      'Fully automatic cooking cycle',
      'Non-stick removable inner pot',
      'Keep-warm function after cooking completes',
      'Tempered glass lid to monitor cooking progress',
      'Cool-touch handles for safety',
    ],
    images: ['/pixel-rice-cooker-250.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.3,
    reviewCount: 59,
    tags: ['pixel', 'rice-cooker', 'electric'],
    createdAt: '2024-01-28',
  },

  // ── Fans ───────────────────────────────────────────────────────
  {
    id: '20',
    name: 'Midea Stand Fan',
    slug: 'Midea stand-fan-120k',
    category: 'fans',
    price: 120_000,
    shortDescription: 'Lightweight 3-speed stand fan for everyday cooling.',
    description:
      'A reliable and affordable stand fan that provides consistent airflow to keep your home comfortable. With three speed settings and wide oscillation, it distributes cool air evenly across the room.',
    features: [
      '3-speed settings for customisable airflow',
      'Wide oscillation for room-wide coverage',
      'Adjustable height stand',
      'Safety blade guard',
      'Quiet motor operation',
    ],
    images: ['/fan120k.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.0,
    reviewCount: 134,
    tags: ['fan', 'stand-fan', 'cooling'],
    createdAt: '2024-01-08',
  },
  {
    id: '21',
    name: 'Deluxe Stand Fan',
    slug: 'stand-fan-130k',
    category: 'fans',
    price: 130_000,
    shortDescription: 'Sturdy stand fan with improved airflow and quiet motor.',
    description:
      'The Deluxe Stand Fan offers improved airflow performance and whisper-quiet operation. Ideal for bedrooms and offices, it keeps the air circulating comfortably without disruptive noise.',
    features: [
      'Enhanced airflow blade design',
      '3-speed settings with quiet motor',
      '90° oscillation for wide-area cooling',
      'Adjustable tilt angle',
      'Stable weighted base for safe placement',
    ],
    images: ['/fan130k.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.1,
    reviewCount: 98,
    tags: ['fan', 'stand-fan', 'cooling'],
    createdAt: '2024-01-10',
  },
  {
    id: '22',
    name: 'Premium Stand Fan',
    slug: 'stand-fan-150k',
    category: 'fans',
    price: 150_000,
    shortDescription: 'Powerful premium stand fan with wide 90° oscillation.',
    description:
      'The Premium Stand Fan delivers powerful cooling performance with a wide 90° oscillation arc. Perfect for larger rooms, it features multiple speed settings and a robust build to suit your comfort needs throughout the day.',
    features: [
      'Powerful motor for strong, consistent airflow',
      '90° oscillation for wide room coverage',
      '3-speed settings',
      'Adjustable height and tilt',
      'Low noise for comfortable daily use',
    ],
    images: ['/fan150k.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.2,
    reviewCount: 87,
    tags: ['fan', 'stand-fan', 'cooling'],
    createdAt: '2024-01-12',
  },
  {
    id: '23',
    name: 'Sonashi Stand Fan',
    slug: 'sonashi-stand-fan',
    category: 'fans',
    price: 150_000,
    shortDescription: 'Sonashi branded stand fan with reliable 3-speed motor.',
    description:
      'The Sonashi Stand Fan is a trusted household fan combining reliable performance with a sleek design. Its 3-speed motor and 90° oscillation ensure cool, circulating air throughout any room.',
    features: [
      'Sonashi quality motor for lasting performance',
      '3-speed settings',
      '90° oscillation',
      'Front and rear safety guard',
      'Simple assembly with no tools needed',
    ],
    images: ['/sonashi-150k-fan.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.2,
    reviewCount: 71,
    tags: ['sonashi', 'fan', 'stand-fan', 'cooling'],
    createdAt: '2024-01-15',
  },
  {
    id: '24',
    name: 'Philips Stand Fan',
    slug: 'philips-stand-fan',
    category: 'fans',
    price: 180_000,
    shortDescription: 'Philips quality stand fan with whisper-quiet operation.',
    description:
      'The Philips Stand Fan brings premium quality cooling to your home. Engineered for quiet and efficient operation, it uses an advanced blade design to move more air with less noise, making it perfect for bedrooms and offices.',
    features: [
      'Philips-engineered quiet motor',
      'Advanced blade design for efficient airflow',
      '3-speed settings',
      '90° oscillation for wide coverage',
      'Adjustable height and tilt angle',
    ],
    images: ['/philips-fan-180k.jpeg'],
    badge: 'Popular',
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.5,
    reviewCount: 143,
    tags: ['philips', 'fan', 'stand-fan', 'cooling'],
    createdAt: '2024-01-18',
  },
  {
    id: '25',
    name: 'Sonash Stand Fan',
    slug: 'sonash-stand-fan',
    category: 'fans',
    price: 180_000,
    shortDescription: 'Sonash stand fan with powerful airflow and oscillation.',
    description:
      'The Sonash Stand Fan delivers strong, consistent airflow to keep any room comfortably cool. With its sturdy build, adjustable settings, and wide oscillation, it is a reliable choice for homes and offices.',
    features: [
      'Powerful airflow motor',
      '3-speed settings',
      'Wide 90° oscillation',
      'Adjustable height stand',
      'Safety blade guard on front and rear',
    ],
    images: ['/Sonash-180k.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.3,
    reviewCount: 52,
    tags: ['sonash', 'fan', 'stand-fan', 'cooling'],
    createdAt: '2024-01-20',
  },

  // ── Blenders ───────────────────────────────────────────────────
  {
    id: '26',
    name: 'Hoffmans Blender 1.5L',
    slug: 'hoffmans-blender-1-5l',
    category: 'blenders',
    price: 200_000,
    shortDescription: 'Compact Hoffmans blender for smoothies, juices and soups.',
    description:
      'The Hoffmans 1.5L Blender is a versatile kitchen appliance for blending smoothies, juices, soups, and sauces. Its powerful motor and durable stainless steel blades handle both soft fruits and harder ingredients with ease.',
    features: [
      '1.5L BPA-free blending jar',
      'Powerful motor for smooth, lump-free results',
      'Multiple speed settings',
      'Stainless steel blades',
      'Easy-clean design with removable base',
    ],
    images: ['/Hoffmans-blender-200k.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.3,
    reviewCount: 65,
    tags: ['hoffmans', 'blender', 'smoothie'],
    createdAt: '2024-02-05',
  },
  {
    id: '27',
    name: 'Hoffmans Blender 2L',
    slug: 'hoffmans-blender-2l',
    category: 'blenders',
    price: 300_000,
    shortDescription: 'Large-capacity Hoffmans blender with pulse function.',
    description:
      'The Hoffmans 2L Blender is built for larger households that need more blending power. With a bigger jar, pulse function, and a more powerful motor, it handles everything from ice crushing to whole-fruit juicing.',
    features: [
      '2L large-capacity BPA-free blending jar',
      'Higher-power motor for tough ingredients',
      'Pulse function for precise blending control',
      'Ice-crushing capability',
      'Stainless steel blades with safety lock lid',
    ],
    images: ['/Hoffmans-blender-300k.jpeg'],
    badge: 'New Arrival',
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.5,
    reviewCount: 49,
    tags: ['hoffmans', 'blender', 'large-capacity'],
    createdAt: '2024-02-08',
  },
  {
    id: '28',
    name: 'Saachi Extension Cord',
    slug: 'saachi-extension-cord',
    category: 'extension-cords',
    price: 50_000,
    shortDescription: 'Saachi multi-socket extension cord for home and office use.',
    description:
      'The Saachi Extension Cord provides extra reach and multiple sockets to power all your appliances safely. Built with surge protection and a durable cable, it is ideal for home, office, and workshop use.',
    features: [
      'Multiple power sockets',
      'Built-in surge protection',
      'Durable heavy-duty cable',
      'Indicator light for power status',
      'Safe flat plug for easy wall insertion',
    ],
    images: ['/saachi-50k.jpeg'],
    inStock: true,
    warranty: '6 months manufacturer warranty',
    rating: 4.0,
    reviewCount: 29,
    tags: ['saachi', 'extension-cord', 'power'],
    createdAt: '2024-02-15',
  },

  // ── Small Appliances ───────────────────────────────────────────
  {
    id: '29',
    name: 'Electric Coffee Maker',
    slug: 'electric-coffee-maker',
    category: 'small-appliances',
    price: 250_000,
    shortDescription: 'Drip coffee maker for fresh, aromatic brews every morning.',
    description:
      'Start your morning right with the Electric Coffee Maker. It brews rich, aromatic coffee quickly and keeps it warm with its integrated hot plate. Simple to use and easy to clean, it is perfect for coffee lovers at home and in the office.',
    features: [
      'Drip brewing system for rich, full-bodied coffee',
      'Built-in keep-warm hot plate',
      'Reusable filter basket included',
      'Water level indicator for easy filling',
      'Compact countertop design',
    ],
    images: ['/Coffee-maker-250k.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.4,
    reviewCount: 82,
    tags: ['coffee-maker', 'coffee', 'appliance'],
    createdAt: '2024-02-10',
  },
  {
    id: '30',
    name: 'Geepas Fan Heater',
    slug: 'geepas-fan-heater',
    category: 'small-appliances',
    price: 180_000,
    shortDescription: 'Geepas fan heater for efficient room heating.',
    description:
      'The Geepas Fan Heater is a compact and efficient heating solution for any room. With adjustable heat settings and a safety shut-off feature, it provides consistent warmth without overheating.',
    features: [
      'Adjustable heat settings',
      'Safety shut-off when tilted',
      'Quiet operation',
      'Energy-efficient design',
      'Stable base with non-slip feet',
    ],
    images: ['/Geepas%20Warmer.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.2,
    reviewCount: 37,
    tags: ['geepas', 'fan-heater', 'heater'],
    createdAt: '2024-01-25',
  },
  {
    id: '31',
    name: 'Hoffmans Pressure Cooker',
    slug: 'hoffmans-pressure-cooker',
    category: 'small-appliances',
    price: 300_000,
    shortDescription: 'Hoffmans stainless steel pressure cooker for fast cooking.',
    description:
      'The Hoffmans Pressure Cooker cuts cooking time significantly while locking in nutrients and natural flavour. Made from durable stainless steel, it features multiple safety mechanisms and is suitable for all hob types including gas and electric.',
    features: [
      'Heavy-duty stainless steel body',
      'Multiple safety valves and locking lid',
      'Reduces cooking time by up to 70%',
      'Suitable for gas and electric hobs',
      'Includes steam rack and recipe guide',
    ],
    images: ['/hoffmans-pressure-cooker.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.4,
    reviewCount: 61,
    tags: ['hoffmans', 'pressure-cooker', 'cooking'],
    createdAt: '2024-02-01',
  },
  {
    id: '32',
    name: 'Multi-Tier Electric Food Steamer',
    slug: 'multi-tier-electric-food-steamer',
    category: 'small-appliances',
    price: 200_000,
    shortDescription: 'Multi-tier electric steamer for healthy, oil-free meals.',
    description:
      'The Multi-Tier Electric Food Steamer provides a healthy way to cook vegetables, fish, dumplings, and more without oil. Its stackable tier design lets you cook different foods simultaneously, saving time while retaining vitamins and nutrients.',
    features: [
      'Multi-tier stackable design for simultaneous cooking',
      'Transparent lids to monitor food without opening',
      'Built-in water reservoir with level indicator',
      'Auto shutoff when water runs dry',
      'Includes rice bowl insert',
    ],
    images: ['/steamer-200k.jpeg'],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.3,
    reviewCount: 44,
    tags: ['steamer', 'electric-steamer', 'healthy-cooking'],
    createdAt: '2024-01-30',
  },
]

export const categories: CategoryMeta[] = [
  {
    id: 'refrigerators',
    label: 'Refrigerators',
    icon: '🧊',
    image: '/fridge-single-350.jpeg',
    description: 'Keep food fresh longer',
    count: 2,
  },
  {
    id: 'washing-machines',
    label: 'Washing Machines',
    icon: '🫧',
    image: '/midea-washing-1.7m.jpeg',
    description: 'Clean clothes effortlessly',
    count: 3,
  },
  {
    id: 'televisions',
    label: 'Televisions',
    icon: '📺',
    image: '/chiq-40inch-700k.jpeg',
    description: 'Stunning displays for every room',
    count: 2,
  },
  {
    id: 'cookers',
    label: 'Cookers',
    icon: '🍳',
    image: '/spj-cooker-990k.jpeg',
    description: 'Gas and electric cookers for every kitchen',
    count: 8,
  },
  {
    id: 'air-fryers',
    label: 'Air Fryers',
    icon: '♨️',
    image: '/kenwood-airfryer-400k.jpeg',
    description: 'Crispy food with less oil',
    count: 2,
  },
  {
    id: 'rice-cookers',
    label: 'Rice Cookers',
    icon: '🍚',
    image: '/oriamo-rice-cooker-250k.jpeg',
    description: 'Perfect rice every time',
    count: 2,
  },
  {
    id: 'fans',
    label: 'Fans',
    icon: '💨',
    image: '/philips-fan-180k.jpeg',
    description: 'Powerful cooling solutions',
    count: 6,
  },
  {
    id: 'blenders',
    label: 'Blenders',
    icon: '🥤',
    image: '/Hoffmans-blender-300k.jpeg',
    description: 'Smooth blends every time',
    count: 2,
  },
  {
    id: 'extension-cords',
    label: 'Extension Cords',
    icon: '🔌',
    image: '/saachi-50k.jpeg',
    description: 'Safe and reliable power extensions',
    count: 1,
  },
  {
    id: 'small-appliances',
    label: 'Small Appliances',
    icon: '⚡',
    image: '/Coffee-maker-250k.jpeg',
    description: 'Coffee makers, steamers, warmers and more',
    count: 4,
  },
]

export const getFeaturedProducts = () =>
  products.filter((p) => p.badge).slice(0, 4)

export const getProductBySlug = (slug: string) =>
  products.find((p) => p.slug === slug)

export const getRelatedProducts = (product: Product, limit = 4) =>
  products
    .filter((p) => p.category === product.category && p.id !== product.id)
    .slice(0, limit)
