import type { Product, CategoryMeta } from './types'

// Using high-quality placeholder images from Unsplash (appliance themed)
const IMG = {
  fridge1: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=600&q=80',
  fridge2: 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&q=80',
  washer1: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=600&q=80',
  washer2: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=600&q=80',
  tv1: 'https://images.unsplash.com/photo-1593359677879-a4bb92f4e4da?w=600&q=80',
  tv2: 'https://images.unsplash.com/photo-1461151304267-38535e780c79?w=600&q=80',
  ac1: 'https://images.unsplash.com/photo-1563452965085-2e77e5bf2607?w=600&q=80',
  micro1: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=600&q=80',
  dispenser1: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
  blender1: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=600&q=80',
  fan1: 'https://images.unsplash.com/photo-1563208723-c0de4814f27a?w=600&q=80',
}

export const products: Product[] = [
  {
    id: '1',
    name: 'Samsung 350L Double Door Refrigerator',
    slug: 'samsung-350l-double-door-refrigerator',
    category: 'refrigerators',
    price: 2_850_000,
    originalPrice: 3_200_000,
    shortDescription: 'No-frost double door fridge with digital inverter technology.',
    description:
      'The Samsung 350L Double Door Refrigerator combines style with powerful cooling. The Digital Inverter Compressor automatically adjusts its speed in response to cooling demand, saving energy and working quietly. Twin Cooling Plus keeps food fresher longer by maintaining optimal humidity levels.',
    features: [
      'Twin Cooling Plus™ technology',
      'Digital Inverter Compressor – 10-year warranty',
      'No Frost – never defrost manually',
      'Door Alarm – alerts when door left open',
      'LED Lighting for energy efficiency',
      'Capacity: 350 Litres (Fridge 255L + Freezer 95L)',
    ],
    images: [IMG.fridge1, IMG.fridge2],
    badge: 'Best Seller',
    inStock: true,
    warranty: '2 years manufacturer warranty',
    rating: 4.8,
    reviewCount: 124,
    tags: ['samsung', 'fridge', 'double-door', 'no-frost'],
    createdAt: '2024-01-10',
  },
  {
    id: '2',
    name: 'LG 260L Single Door Refrigerator',
    slug: 'lg-260l-single-door-refrigerator',
    category: 'refrigerators',
    price: 1_750_000,
    shortDescription: 'Efficient single door fridge perfect for small families.',
    description:
      'The LG 260L Single Door Refrigerator is designed for efficiency and reliability. Smart Inverter Compressor technology reduces energy consumption while maintaining optimal cooling performance throughout the day.',
    features: [
      'Smart Inverter Compressor',
      'Multi Air Flow system',
      'Auto Smart Connect',
      'Toughened glass shelves',
      'Capacity: 260 Litres',
      '10-year compressor warranty',
    ],
    images: [IMG.fridge2, IMG.fridge1],
    inStock: true,
    warranty: '2 years manufacturer warranty',
    rating: 4.6,
    reviewCount: 87,
    tags: ['lg', 'fridge', 'single-door'],
    createdAt: '2024-01-15',
  },
  {
    id: '3',
    name: 'Samsung 8KG Front Load Washing Machine',
    slug: 'samsung-8kg-front-load-washing-machine',
    category: 'washing-machines',
    price: 2_200_000,
    originalPrice: 2_600_000,
    shortDescription: 'AI-powered front loader with EcoBubble technology.',
    description:
      'The Samsung 8KG Front Load Washing Machine uses EcoBubble technology to generate bubbles that penetrate fabrics quickly for effective cleaning even in cold water, saving energy without sacrificing performance.',
    features: [
      'EcoBubble™ technology',
      'Digital Inverter Motor – 10-year warranty',
      'Hygiene Steam cycle',
      'AI Control – auto-adjusts wash settings',
      '15-minute Quick Wash',
      '8KG capacity with 1400 RPM spin',
    ],
    images: [IMG.washer1, IMG.washer2],
    badge: 'New Arrival',
    inStock: true,
    warranty: '2 years + 10 years motor warranty',
    rating: 4.9,
    reviewCount: 203,
    tags: ['samsung', 'washing-machine', 'front-load', 'eco'],
    createdAt: '2024-02-01',
  },
  {
    id: '4',
    name: 'Hisense 7KG Top Load Washing Machine',
    slug: 'hisense-7kg-top-load-washing-machine',
    category: 'washing-machines',
    price: 1_100_000,
    shortDescription: 'Reliable top loader with powerful wash performance.',
    description:
      'The Hisense 7KG Top Load Washing Machine delivers reliable, powerful cleaning at a great value. Multiple wash programs accommodate all fabric types while the large drum handles family-sized loads with ease.',
    features: [
      'Fuzzy Logic Control system',
      '12 wash programs',
      'Air Dry function',
      'Child lock safety feature',
      '7KG capacity',
      'Low water consumption',
    ],
    images: [IMG.washer2, IMG.washer1],
    inStock: true,
    warranty: '2 years manufacturer warranty',
    rating: 4.4,
    reviewCount: 56,
    tags: ['hisense', 'washing-machine', 'top-load'],
    createdAt: '2024-01-20',
  },
  {
    id: '5',
    name: 'Samsung 55" 4K QLED Smart TV',
    slug: 'samsung-55-4k-qled-smart-tv',
    category: 'televisions',
    price: 3_500_000,
    originalPrice: 4_100_000,
    shortDescription: 'Stunning QLED display with Quantum Processor 4K.',
    description:
      'Experience cinema-quality viewing with the Samsung 55" 4K QLED Smart TV. Quantum Dot technology delivers a billion shades of brilliant color, while the Quantum Processor 4K upscales content to near 4K quality automatically.',
    features: [
      'Quantum HDR 12X for exceptional brightness',
      'Object Tracking Sound for immersive audio',
      'Tizen Smart TV with built-in streaming apps',
      'Motion Xcelerator Turbo for gaming at 120fps',
      '55-inch 4K QLED panel',
      '4 HDMI ports, 2 USB ports',
    ],
    images: [IMG.tv1, IMG.tv2],
    badge: 'Premium',
    inStock: true,
    warranty: '3 years manufacturer warranty',
    rating: 4.9,
    reviewCount: 312,
    tags: ['samsung', 'tv', 'qled', '4k', 'smart-tv'],
    createdAt: '2024-01-05',
  },
  {
    id: '6',
    name: 'Hisense 43" Full HD Smart TV',
    slug: 'hisense-43-full-hd-smart-tv',
    category: 'televisions',
    price: 1_350_000,
    shortDescription: 'Smart TV with DTS Virtual X audio and VIDAA Smart system.',
    description:
      'The Hisense 43" Smart TV offers fantastic value with its Full HD display, VIDAA smart platform, and DTS Virtual X immersive sound. Perfect for bedrooms, living rooms, and small apartments.',
    features: [
      'Full HD 1080p display',
      'VIDAA Smart TV platform',
      'DTS Virtual X audio',
      'Dolby Audio',
      'Screen mirroring & casting',
      '2 HDMI + 2 USB ports',
    ],
    images: [IMG.tv2, IMG.tv1],
    inStock: true,
    warranty: '2 years manufacturer warranty',
    rating: 4.5,
    reviewCount: 178,
    tags: ['hisense', 'tv', 'smart-tv', 'full-hd'],
    createdAt: '2024-01-18',
  },
  {
    id: '7',
    name: 'Midea 1.5HP Split Air Conditioner',
    slug: 'midea-1-5hp-split-air-conditioner',
    category: 'air-conditioners',
    price: 2_100_000,
    shortDescription: 'Inverter AC with smart control and rapid cooling.',
    description:
      'The Midea 1.5HP Inverter Split AC combines powerful cooling with energy efficiency. The variable-speed compressor maintains temperature precisely, saving up to 60% on electricity compared to conventional ACs.',
    features: [
      'DC Inverter Compressor technology',
      'Wi-Fi Smart Control via app',
      'Self-Cleaning function',
      '4-way auto swing',
      'Sleep mode for quiet nights',
      'R32 eco-friendly refrigerant',
    ],
    images: [IMG.ac1],
    inStock: true,
    warranty: '2 years + 5 years compressor warranty',
    rating: 4.7,
    reviewCount: 91,
    tags: ['midea', 'air-conditioner', 'inverter', 'split'],
    createdAt: '2024-02-10',
  },
  {
    id: '8',
    name: 'LG 25L Solo Microwave Oven',
    slug: 'lg-25l-solo-microwave-oven',
    category: 'microwaves',
    price: 520_000,
    shortDescription: 'Sleek solo microwave with smart inverter technology.',
    description:
      'The LG 25L Solo Microwave offers consistent, even cooking using smart inverter technology. The intuitive touch controls and auto-cook menus make meal preparation quick and effortless.',
    features: [
      'Smart Inverter Technology',
      'Even reheating throughout',
      '25L capacity',
      'Auto-cook menus',
      'EasyClean® interior',
      '5 power levels',
    ],
    images: [IMG.micro1],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.5,
    reviewCount: 64,
    tags: ['lg', 'microwave', 'inverter'],
    createdAt: '2024-01-25',
  },
  {
    id: '9',
    name: 'Nunix Hot & Cold Water Dispenser',
    slug: 'nunix-hot-cold-water-dispenser',
    category: 'water-dispensers',
    price: 380_000,
    shortDescription: 'Premium floor-standing dispenser with hot & cold taps.',
    description:
      'The Nunix Hot & Cold Water Dispenser provides instant access to perfectly chilled or hot water at any time. The child-safe hot water tap and elegant design make it ideal for both home and office use.',
    features: [
      'Hot & Cold & Normal water',
      'Child-safe hot water lock',
      'Floor-standing design',
      'Large capacity tanks',
      'LED temperature indicators',
      'Energy-saving mode',
    ],
    images: [IMG.dispenser1],
    badge: 'Popular',
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.3,
    reviewCount: 145,
    tags: ['nunix', 'water-dispenser', 'hot-cold'],
    createdAt: '2024-01-12',
  },
  {
    id: '10',
    name: 'Blendjet Portable Blender Pro',
    slug: 'blendjet-portable-blender-pro',
    category: 'blenders',
    price: 220_000,
    shortDescription: 'Powerful portable blender – USB rechargeable.',
    description:
      'The Blendjet Portable Blender Pro blends smoothies, shakes, and juices anywhere in seconds. USB-C rechargeable with 20 full blends per charge, it is the perfect companion for active lifestyles.',
    features: [
      'USB-C rechargeable',
      '20 blends per charge',
      'Self-cleaning cycle',
      'Leak-proof lid',
      'BPA-free materials',
      'Available in multiple colors',
    ],
    images: [IMG.blender1],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.6,
    reviewCount: 89,
    tags: ['blender', 'portable', 'usb'],
    createdAt: '2024-02-05',
  },
  {
    id: '11',
    name: 'Binatone 16" Stand Fan',
    slug: 'binatone-16-stand-fan',
    category: 'fans',
    price: 185_000,
    shortDescription: 'Powerful 3-speed stand fan with oscillation.',
    description:
      'The Binatone 16-inch Stand Fan delivers strong, consistent airflow across a wide area. Three speed settings, 90° oscillation, and an adjustable height stand offer flexible cooling for any room.',
    features: [
      '3-speed settings',
      '90° oscillation',
      'Adjustable height stand',
      'Safety blade guard',
      'Easy assembly',
      'Low noise motor',
    ],
    images: [IMG.fan1],
    inStock: true,
    warranty: '1 year manufacturer warranty',
    rating: 4.2,
    reviewCount: 203,
    tags: ['binatone', 'fan', 'stand-fan'],
    createdAt: '2024-01-08',
  },
  {
    id: '12',
    name: 'Samsung 500L French Door Refrigerator',
    slug: 'samsung-500l-french-door-refrigerator',
    category: 'refrigerators',
    price: 5_200_000,
    originalPrice: 6_000_000,
    shortDescription: 'Luxury french door fridge with Family Hub display.',
    description:
      'The Samsung 500L French Door Refrigerator is the ultimate smart kitchen appliance. The built-in Family Hub touchscreen display lets you manage your home, stream music, and see inside your fridge from anywhere using your smartphone.',
    features: [
      'Family Hub 21.5" touchscreen',
      'View Inside – 3 interior cameras',
      'Bespoke design customizable panels',
      'Twin Cooling Plus™',
      'FlexZone™ convertible compartment',
      '500L total capacity',
    ],
    images: [IMG.fridge1, IMG.fridge2],
    badge: 'Luxury',
    inStock: true,
    warranty: '5 years comprehensive warranty',
    rating: 4.9,
    reviewCount: 47,
    tags: ['samsung', 'fridge', 'french-door', 'smart', 'luxury'],
    createdAt: '2024-02-15',
  },
]

export const categories: CategoryMeta[] = [
  { 
    id: 'refrigerators',    
    label: 'Refrigerators',    
    icon: '🧊', 
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80',
    description: 'Keep food fresh longer', 
    count: 3 
  },
  { 
    id: 'washing-machines', 
    label: 'Washing Machines',  
    icon: '🫧', 
    image: 'https://images.unsplash.com/photo-1545173153-936277a8bba1?w=600&q=80',
    description: 'Clean clothes effortlessly', 
    count: 2 
  },
  { 
    id: 'televisions',      
    label: 'Televisions',       
    icon: '📺', 
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f4e4da?w=600&q=80',
    description: 'Stunning displays for every room', 
    count: 2 
  },
  { 
    id: 'air-conditioners', 
    label: 'Air Conditioners',  
    icon: '❄️', 
    image: 'https://images.unsplash.com/photo-1563452965085-2e77e5bf2607?w=600&q=80',
    description: 'Cool comfort year-round', 
    count: 1 
  },
  { 
    id: 'microwaves',       
    label: 'Microwaves',        
    icon: '🍽️', 
    image: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=600&q=80',
    description: 'Fast & even cooking', 
    count: 1 
  },
  { 
    id: 'water-dispensers', 
    label: 'Water Dispensers',  
    icon: '💧', 
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    description: 'Hot & cold at the push of a button', 
    count: 1 
  },
  { 
    id: 'blenders',         
    label: 'Blenders',          
    icon: '🥤', 
    image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=600&q=80',
    description: 'Smooth blends every time', 
    count: 1 
  },
  { 
    id: 'fans',             
    label: 'Fans',              
    icon: '💨', 
    image: 'https://images.unsplash.com/photo-1563208723-c0de4814f27a?w=600&q=80',
    description: 'Powerful cooling solutions', 
    count: 1 
  },
]

export const getFeaturedProducts = () =>
  products.filter((p) => p.badge).slice(0, 4)

export const getProductBySlug = (slug: string) =>
  products.find((p) => p.slug === slug)

export const getRelatedProducts = (product: Product, limit = 4) =>
  products
    .filter((p) => p.category === product.category && p.id !== product.id)
    .slice(0, limit)